export const lineThickness = 1
export const hoverTrapSizeFromOneSide = 20
export const yTranslate = '20px'
export const lineColor = 'hsla(0, 0%, 80%, 0.7)'
export const circleColor = 'hsl(0, 0%, 70%)'
// export const circleColor = 'hsl(0, 0%, 80%)'
export const textColor = '#666666'
// export const STROKE_DASHARRAY = '40 20'
export const STROKE_DASHARRAY = '34 17'
