// TODO: tasks that depend on other tasks
export enum PRIORITY {
  BEFORE_RENDER,
  READ,
  COMPUTE,
  WRITE,
}

export const BEFORE_RENDER_PRIORITIES_IN_ORDER = [PRIORITY.BEFORE_RENDER]

export const RENDER_PRIORITIES_IN_ORDER = [
  PRIORITY.READ,
  PRIORITY.COMPUTE,
  PRIORITY.WRITE,
]

export const PRIORITIES_IN_ORDER = [
  ...BEFORE_RENDER_PRIORITIES_IN_ORDER,
  ...RENDER_PRIORITIES_IN_ORDER,
]
